name: core_catalogo_module
description: A new flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  http: ^0.13.4
  injectable: ^1.5.3
  internet_connection_checker: ^0.0.1+3
  isar: ^2.2.1
  isar_flutter_libs: ^2.2.1
  json_annotation: ^4.3.0
  path_provider: ^2.0.9

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  isar_generator: ^2.2.1
  json_serializable: ^6.1.5
  build_runner: ^2.1.8
  injectable_generator: ^1.5.3


flutter:

  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.core_catalogo_module
    iosBundleIdentifier: com.example.coreCatalogoModule
